QuanLySach/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using QuanLySach.Models;

namespace BookStore.Controllers
{
    public class NguoiDungController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: NguoiDung
        string LayMaKH()
        {
            var maMax = db.KhachHangs.ToList().Select(n => n.MaKH).Max();
            if (maMax == null)
                return "KH001";
            string so = maMax.Substring(2);

            // Chuyển đổi số thành giá trị số nguyên
            int soHienTai = int.Parse(so);

            // Tăng giá trị số hiện tại lên 1
            int soMoi = soHienTai + 1;

            // Tạo mã HD mới bằng cách kết hợp "KH" với số mới đã định dạng
            string maKH = "KH" + soMoi.ToString("D3");

            return maKH;
        }
        public ActionResult Index()
        {
            return View();
        }
        // Get DangKi 
        public ActionResult DangKi()
        {
            return View();
        }

        //Get thong tin nguoi dung 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKi(KhachHang kh)
        {//neu hop le thy cho them vao
            if (ModelState.IsValid)
            {
                kh.MaKH = LayMaKH();
                db.KhachHangs.Add(kh);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(kh);
        }

        // Get Dang Nhap
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            string tk = f["txtTaiKhoan"].ToString();
            string mk = f["txtMatKhau"].ToString();
            if (tk == "" || mk == "")
            {
                ViewBag.ThongBao = "BẠN CHƯA NHẬP TÀI KHOẢN HOẶC MẬT KHẨU";
                return View();
            }
            Session["ID"] = null;
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == tk && n.MatKhau == mk);
            tbl_Login admin = db.tbl_Login.SingleOrDefault(n => n.Username == tk && n.Password == mk);
            
            if (kh != null)
            {
                Session["TaiKhoan"] = kh;
                Session["ID"] = kh.MaKH;
                return RedirectToAction("Index", "Home");
            }
            else if (admin != null)
            {
                Session["TaiKhoanAdmin"] = admin;
                return RedirectToAction("Index", "Admin");
            }

            ViewBag.ThongBao = "TÊN TÀI KHOẢN HOẶC MẬT KHẨU CỦA BẠN KHÔNG ĐÚNG";
            return View();
        }

        // GET: NguoiDung/DangXuat
        public ActionResult DangXuat()
        {
            // Xóa phiên đăng nhập của người dùng
            Session["TaiKhoan"] = null;
            Session["TaiKhoanAdmin"] = null;

            // Chuyển hướng về trang đăng nhập
            return RedirectToAction("../Home/Index");
        }

    }
}

QuanLySach/Views/NguoiDung/DangKi.cshtml
@model QuanLySach.Models.KhachHang


@{
    ViewBag.Title = "DangKi";

}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div style="border: hidden 1px; border-radius: 10px; background-color: gainsboro; padding: 50px; margin: 10px 5px 5px 0;">
                <h2 style="text-align:center">ĐĂNG KÝ</h2>
                <br />
                <div>
                    @using (Html.BeginForm("DangKi", "NguoiDung", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal" style="margin-left: 20%; margin-right: 0%">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.MaKH)
                            <div class="form-group">
                                <div class="col-md-10">
                                    <span id="Hoten"></span>
                                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control", placeholder = "Họ và tên" } })
                                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })

                                </div>
                            </div>
                            <div class="form-group">

                                <div class="col-md-10">
                                    <span id="Taikhoan"></span>
                                    @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control", placeholder = "Tài khoản" } })
                                    @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", placeholder = "Mật khẩu", id = "MatKhau", type = "password" } })
                                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", placeholder = "Địa chỉ" } })
                                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control", placeholder = "Điện thoại" } })
                                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="checkboxradio">
                                        <label class="radio-inline">
                                            @Html.RadioButtonFor(model => model.GioiTinh, true) Nam
                                        </label>
                                        <label class="radio-inline">
                                            @Html.RadioButtonFor(model => model.GioiTinh, false) Nữ
                                        </label>
                                        @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group" style="margin-left:-29px">

                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control", placeholder = "Ngày sinh" } })
                                    @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="col-md-10" style="text-align:center">
                                    <button type="submit" class="button button-submit" style="border-radius:10px; margin-bottom:30px">Đăng ký</button>
                                </div>
                                <div class="col-md-10" style="text-align: center">
                                    <a href="@Url.Action("index","Home")" class="btn btn-default" style="border-radius: 10px; ">Trở về</a>
                                </div>

                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#btnDangKi').click(function () {
        var loi = 0;
        if ($('#HoTen').val() == "") {
            $('#Hoten').text("Chưa nhập họ tên!.");
            loi++;
        }
        else {
            $('#Hoten').text("");
        }
        if ($('#TaiKhoan').val() == "") {
            $('#Taikhoan').text("Chưa nhập tài khoản!.");
            loi++;
        }
        else
            $('#Taikhoan').text("");
        return false;

        if (loi != 0) {
            return false;
        }
        else {
            return true;
        }
    });

</script>

QuanLySach/Views/NguoiDung/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
}
<div style="border: hidden 1px; background-color: gainsboro; padding: 50px; border-radius: 10px; margin-left: 25%; margin-right: 25%; ">
    <h2 style="font-weight:bold;text-align:center">Đăng Nhập</h2>
    <br />
    <div class="DangNhap">
        @using (Html.BeginForm())
        {
            <h1>@ViewBag.ThongBao</h1>
            <div >
                @Html.TextBox("txtTaiKhoan", "", htmlAttributes: new { @class = "txtTaiKhoan", @placeholder = "Hãy nhập tài khoản" })<br /><br />
            </div>
            <div class="password-input" >
                @Html.Password("txtMatKhau", "", htmlAttributes: new { @class = "txtMatKhau", @placeholder = "Hãy nhập mật khẩu" })
            </div>
            <br /><br />
            <input id="btnDangNhap" type="submit" value="Đăng Nhập" class="button" style="border-radius:10px" />
        }
    </div>
</div>
<style>
    #txtTaiKhoan {
        border: 4px solid #ccc;
        border-radius:10px;
    }

    #txtMatKhau {
        border: 5px solid #ccc;
        border-radius: 10px;
    }

    .DangNhap {
        text-align: center;
    }

    .password-input {
        position: relative;
        display: inline-block;
    }

    .toggle-password {
        position: absolute;
        top: 50%;
        right: 10px;
        transform: translateY(-50%);
        cursor: pointer;
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var togglePassword = document.querySelector(".toggle-password");
        var passwordInput = document.querySelector(".txtMatKhau");

        togglePassword.addEventListener("click", function () {
            if (passwordInput.type === "password") {
                passwordInput.type = "text";
            } else {
                passwordInput.type = "password";
            }
        });
    });
</script>

QuanLySach/Views/NguoiDung/DangXuat.cshtml
@{
    ViewBag.Title = "DangXuat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Đăng Xuất</title>
</head>
<body>
    <div>
        <h2>Đăng Xuất</h2>
        <p>Bạn đã đăng xuất thành công.</p>
        <p><a href="@Url.Action("DangNhap", "NguoiDung")">Đăng nhập lại</a></p>
    </div>
</body>
</html>