QuanLySach/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
        // Gioi Thieu
        public ActionResult GioiThieu()
        {
            return View();
        }
        //Lien He
        public ActionResult LienHe()
        {
            return View();
        }
        // Tin tuc :
        public ActionResult TinTuc()
        {
            return View();
        }

    }
}

QuanLySach/Controllers/AdminController.cs
using PagedList;
using QuanLySach.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class AdminController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: Admin
        // Index Sach :
        public ActionResult Index(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 4;

            return View(db.Saches.ToList().OrderBy(n => n.MaSach).ToPagedList(pageNum, pageSize));
        }
        //Index DatHang :
        public ActionResult IndexDH(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 4;

            return View(db.DonHangs.ToList().OrderByDescending(n => n.MaDonHang).ToPagedList(pageNum, pageSize));
        }
        //Index ChiTietDonHang :
        public ActionResult IndexCTDH(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 4;

            return View(db.ChiTietDonHangs.ToList().OrderByDescending(n => n.MaDonHang).ToPagedList(pageNum, pageSize));
        }

        // Get add sach
        [HttpGet]
        public ActionResult ThemMoi()
        {
            ViewBag.MachuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            return View();
        }
        /*
        [HttpPost]
        public ActionResult ThemMoi(Sach sach,HttpPostedFileBase  fileUpload)
        {
            //luu ten cua file.

            var fileName = Path.GetFileName(fileUpload.FileName);

            //luu duong dan cua file.
            var path = Path.Combine(Server.MapPath("~/HinhAnhSP"),fileName);

            if (System.IO.File.Exists(path))
            {
               ViewBag.ThongBao = "Hình Ảnh đã tồn tại.";
            }
            else
            {
                fileUpload.SaveAs(path);
            }
            ViewBag.MachuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

            return View();
        }
        */
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(Sach sach, HttpPostedFileBase fileUpload)
        {


            //dua du lieu vao dropdowlist.
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

            //kiem tra duong dan anh bia.
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }

            //them vao co so du lieu.
            if (ModelState.IsValid)
            {
                //luu ten cua file.
                var fileName = Path.GetFileName(fileUpload.FileName);
                //luu duong dan cua file.
                var path = Path.Combine(Server.MapPath("~/HinhAnhSP"), fileName);
                //kiem tra hinh anh da ton tai chua.
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sach.AnhBia = fileUpload.FileName;
                db.Saches.Add(sach);
                db.SaveChanges();
            }
            return View();

        }

        //Get edit sach :
        [HttpGet]
        public ActionResult ChinhSua(string MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            return View(sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(Sach sach, FormCollection f)
        {
            if (ModelState.IsValid)
            {
                //cập nhật.
                db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            return RedirectToAction("Index");
        }

        // Hien thi 
        public ActionResult HienThi(string MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }

        //Get sach :
        [HttpGet]
        public ActionResult Xoa(string MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpPost]
        [ActionName("XoaXacNhan")]
        public ActionResult XacNhanXoa(string MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        


        [HttpGet]
        public ActionResult BaoCaoDoanhThu(int? thang, int? nam)
        {
            if (thang == null || nam == null)
            {
                // Trả về view với giá trị mặc định hoặc thông báo lỗi
                return View();
            }

            string connectionString = "Data Source=LAPTOP\\HAMIN;Initial Catalog=QuanLiBanSach;Integrated Security=True";

            string query = "SELECT MaDonHang, DaThanhToan, TinhTrangGiaoHang, NgayDat, NgayGiao, MaKH, TongTien " +
                           "FROM DonHang " +
                           "WHERE MONTH(NgayDat) = @Thang AND YEAR(NgayDat) = @Nam";

            List<DonHang> danhSachHoaDon = new List<DonHang>();
            decimal tongDoanhThu = 0;

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Thang", thang);
                command.Parameters.AddWithValue("@Nam", nam);

                SqlDataReader reader = command.ExecuteReader();

                while (reader.Read())
                {
                    DonHang hoaDon = new DonHang
                    {
                        MaDonHang = reader.GetString(0),
                        DaThanhToan = reader.GetBoolean(1),
                        TinhTrangGiaoHang = reader.GetBoolean(2),
                        NgayDat = reader.GetDateTime(3),
                        NgayGiao = reader.IsDBNull(4) ? (DateTime?)null : reader.GetDateTime(4),
                        MaKH = reader.GetString(5),
                        TongTien = reader.GetDecimal(6)
                    };

                    danhSachHoaDon.Add(hoaDon);
                    tongDoanhThu += hoaDon.TongTien;
                }
            }

            ViewBag.DanhSachHoaDon = danhSachHoaDon;
            ViewBag.TongDoanhThu = tongDoanhThu;

            return View();
        }
    }
}

QuanLySach/Controllers/ChuDeController.cs
using PagedList;
using QuanLySach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class ChuDeController : Controller
    {
        //db :
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: ChuDe
        public ActionResult Index(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;
            return View(db.ChuDes.ToList().OrderBy(n => n.MaChuDe).ToPagedList(pageNum, pageSize));
        }
        public PartialViewResult ChuDePartial()
        {
            return PartialView(db.ChuDes.Take(5).ToList());
        }
        public ViewResult SachTheoChuDe(string Ma = "")
        {
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == Ma);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<Sach> sach = db.Saches.Where(n => n.MaChuDe == Ma).OrderBy(n => n.GiaBan).ToList();
            if (sach.Count == 0)
            {
                ViewBag.Sach = "Không Có Sách Nào Thuộc Chủ Đề Này";
            }
            return View(sach);
        }
        public ViewResult DanhMucChuDe()
        {
            return View(db.ChuDes.ToList());
        }

        //CRUD chu de :
        //Add chu de 
        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(ChuDe chude)
        {
            if (ModelState.IsValid)
            {
                db.ChuDes.Add(chude);
                db.SaveChanges();
            }
            return View();
        }

    }
}

QuanLySach/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using QuanLySach.Models;

namespace BookStore.Controllers
{
    public class TimKiemController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: TimKiem
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f, int? page)
        {
            //lay tu khoa nhap vao roi tim kiem ben trong co so du lieu.

            string tukhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = tukhoa;
            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(tukhoa)).ToList();
            //phan trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " sản phẩm";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult KetQuaTimKiem(string tukhoa, int? page)
        {
            //lay tu khoa nhap vao roi tim kiem ben trong co so du lieu.
            ViewBag.TuKhoa = tukhoa;

            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(tukhoa)).ToList();
            //phan trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy" + lstKQTK.Count + " San pham.";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }
    }
}

QuanLySach/Views/Shared/_Layout.cshtml
@using QuanLySach.Models

@{
    var taiKhoan = HttpContext.Current.Session["TaiKhoan"] as KhachHang;
    var taiKhoanAdmin = HttpContext.Current.Session["Username"] as tbl_Login;
    var isLoggedIn = taiKhoan != null;
    var isLoggedOut = !isLoggedIn;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nhà sách trực tuyến Nhã Nam</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/fonts.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/nivo-slider.css" rel="stylesheet" />
    <link href="~/Content/css.css" rel="stylesheet" />
    <link href="~/Content/screen.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.nivo.slider.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">


</head>
<style>
    .button-buy {
        background-color: #cfb686;
        color: #fff;
    }
    .icon_account_gray {
        background: url(/skin/frontend/ma_vanese/fahasa/images/ico_account_gray.svg) no-repeat center center;
        _webkit-background-size: contain;
        _moz-background-size: contain;
        _o-background-size: contain;
        background-size: contain;
        height: 24px;
        width: 24px;
        position: relative;
    }

    .dropdown:hover .dropdown-menu {
        display: block;
        background-color: #cfb686;
        color: #fff;
    }

    .dropdown-menu {
        display: none;
        position: absolute;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        padding: 12px 16px;
    }

        .dropdown-menu a {
            color: white;
            text-decoration: none;
            display: block;
        }

            .dropdown-menu a:hover {
                text-decoration: none;
                color: black;
                background-color: white;
            }

    .header-image {
        width: 100%;
        height: 100%;
    }

    .flash {
        background-color: #f2f2f2;
        padding-bottom: 40px;
        padding-top: 20px;
    }

    .dangki_dangnhap {
        display: flex;
        align-items: center;
        justify-content: center;
    }
        .dangki_dangnhap a {
            margin: 0 10px;
            color: #000;
            text-decoration: none;
            font-weight: bold;
        }
    #user-icon {
        color: black;
        width: 20px;
        height: 20px;
        padding-bottom: 20px;
    }
</style>
<body>

    <section class="blank">
        <div class="flash">
            <div style="text-align:start"></div>
            <div class="dangki_dangnhap">
                @if (isLoggedIn)
                {
                    if (taiKhoanAdmin != null) // Kiểm tra vai trò của người dùng đăng nhập
                    {
                        // Hiển thị trang quản trị
                        @Html.ActionLink("Trang Quản Trị", "Index", "Admin", null, htmlAttributes: new { @class = "DangNhap" })
                    }
                    else
                    {
                        @Html.Action("GioHangPartial", "GioHang")
                    }

                    <a href="#" class="fas fa-users" style="text-decoration:none;color:black" onclick="redirectToEditPage()">
                        <br />Thông tin khách hàng
                    </a>

                    <i class="" aria-hidden="true" target="_blank"></i>
                    <div class="icon-logout">
                        <a href="#" class="DangNhap" onclick="confirmLogout()" style="text-decoration:none;color:black">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z" />
                                <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
                            </svg><br />Đăng xuất
                        </a>
                    </div>
                }
                else if (isLoggedOut)
                {
                    @Html.Action("GioHangPartial", "GioHang")
                    <i class="" aria-hidden="true" target="_blank"></i>
                    <div class="dropdown">

                        <a href="#" style="text-decoration:none;color:black; margin:-5px; margin-bottom:30px">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20 " fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
                            </svg><br />Tài khoản
                        </a>
                        <div class="dropdown-menu" style="text-align:center">
                            <div>@Html.ActionLink("Đăng Nhập", "DangNhap", "NguoiDung", null, htmlAttributes: new { @class = "DangNhap" })</div>
                            <div>@Html.ActionLink("Đăng Kí", "DangKi", "NguoiDung", null, htmlAttributes: new { @class = "DangKi" })</div>
                        </div>
                    </div>

                }
            </div>
        </div>
        <div>
            <img src="~/Images/banner.png" alt="Ảnh của bạn" class="header-image" />
        </div>

        <div class="flash success">
            <div class="timkiem">
                @using (Html.BeginForm("KetQuaTimKiem", "TimKiem", FormMethod.Post))
                {
                    @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "TextBoxTimKiem", @placeholder = "Tím kiếm sách " })
                    <button class="btntimkiem" type="submit"></button>
                }
            </div>
            <div class="menu-top" style="color:black">
                <ul>
                    <li><a href="@Url.Action("Index","Home")" style="text-decoration:none;color:aliceblue;"> Trang Chủ</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-link" style="text-decoration:none;color:aliceblue;">Danh mục</a>
                        <div class="dropdown-menu">
                            <a href="@Url.Action("DanhMucNhaXuatBan","NhaXuatBan")">Nhà xuất bản</a>
                            <a href="@Url.Action("DanhMucChuDe","ChuDe")">Chủ đề</a>
                        </div>
                    </li>
                    <li><a href="@Url.Action("GioiThieu","About")" style="text-decoration:none;color:aliceblue;"> Giới Thiệu</a></li>
                    <li><a href="@Url.Action("Index","Home")" style="text-decoration:none;color:aliceblue;"> Sách</a></li>
                    <li><a href="@Url.Action("TinTuc","About")" style="text-decoration:none;color:aliceblue;"> Tin tức</a></li>
                    <li><a href="@Url.Action("LienHe","About")" style="text-decoration:none;color:aliceblue;"> Liên Hệ</a></li>
                </ul>
            </div>

        </div>
    </section>

    <section>

        <div class="noidung" style="margin:1px 1px 1px 1px">
            @RenderBody()
        </div>
    </section>
    <section>
        <div class="footer" style="">
            <div class="end">
                <div class="container">
                    <div class="col-md-6">
                        <div class="footer_container">
                            <h3>QUY ĐỊNH, CHÍNH SÁCH</h3>
                            <p><a href="#" style="color: #a7a7a7">QĐ đổi hàng và hoàn trả tiền</a></p>
                            <p><a href="#" style="color: #a7a7a7">Quy Định</a></p>
                            <p><a href="#" style="color: #a7a7a7">Chính sách cửa hàng</a></p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer_container">
                            <h3>THÔNG TIN NHÓM</h3>
                            <p>Phan Thị Phương Hà</p>
                            <p>Nguyễn Ngọc Đức Nhông</p>
                            <p>Phạm Nguyễn Thiên Lân</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div>
            <a href="#" class="button button-buy">Nhóm 1 - 62.CNTT-2 </a>
        </div>
    </section>
</body>

<script type="text/javascript">
    $(window).load(function () {
        $('#slider').nivoSlider({
        });
    });
</script>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1838823719729580";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script>//Thông báo ĐĂNG XUẤT
    function confirmLogout() {
        var result = confirm("Bạn muốn đăng xuất không?");
        if (result) {
            // Nếu người dùng đồng ý đăng xuất, chuyển hướng đến trang đăng xuất
            window.location.href = "@Url.Action("DangXuat", "NguoiDung")";
        }
    }
</script>

<script>
    function redirectToEditPage() {
        window.location.href =  "@Url.Action("Details", "KhachHang", new { id = Session["ID"] })";
    }
</script>
</html>